apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: oa7dvirav-nodejs-gitops
  description: This is GitOps manifest for oa7dvirav-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: oa7dvirav-nodejs
    janus-idp.io/tekton: oa7dvirav-nodejs 
    backstage.io/kubernetes-id: oa7dvirav-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:oa7dvirav-nodejs
