apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oa7dvirav-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oa7dvirav-nodejs 
  name: oa7dvirav-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: oa7dvirav-nodejs 
